openapi: 3.0.0
info:
  title: API para consulta de ordenes
  version: 1.0.0
servers:
  - url: /  # Reemplazar con la URL de tu Cloud Function
    description: El servidor que aloja la API

# Agregar seguridad global
security:
  - bearerAuth: []

paths:
  /buscarOrden:
    post:
      security:
        - bearerAuth: []
      summary: Consulta una orden por id_evento y orden_compra
      description: Busca una orden específica en la base de datos
      parameters:
        - in: header
          name: auth-token
          schema:
            type: string
          required: true
          description: Token de autenticación requerido
          example: "tu-token-secreto"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_evento:
                  type: integer
                  description: Identificador del evento
                  example: 1
                orden_compra:
                  type: integer
                  description: Identificador de la orden de compra
                  example: 1
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: Datos de la orden encontrada
                    example: {"id_orden": 1,"id_evento": 1,"numero_orden": "ORD-2024-001","fecha_compra": "2025-01-06T22:05:40.980Z","cantidad_boletos": 2,"precio_total": "150.00","estado_pago": "completado","email_comprador": "juan@email.com","nombre_comprador": "Juan Pérez","metodo_pago": "tarjeta","estado_orden": "confirmado","nombre": "Concierto Rock en Vivo","fecha_evento": "2024-06-16T01:00:00.000Z","lugar": "Arena Ciudad","capacidad": 5000,"precio_base": "75.00","estado": "activo","descripcion": "Gran concierto de rock con bandas locales","categoria": "música","created_at": "2025-01-06T22:05:40.980Z"}
                  status:
                    type: integer
                    description: Código de estado HTTP
                    example: 200
        '400':
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    description: Mensaje de error
                    example: Solicitud incorrecta
                  status:
                    type: integer
                    description: Código de estado HTTP
                    example: 400
        '403':
          description: Acceso denegado
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    description: Mensaje de error
                    example: Acceso denegado
                  status:
                    type: integer
                    description: Código de estado HTTP
                    example: 403
        '404':
          description: Orden no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    description: Mensaje de error
                    example: Orden no encontrada
                  status:
                    type: integer
                    description: Código de estado HTTP
                    example: 404
        '405':
          description: Método no permitido
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    description: Mensaje de error
                    example: Método no permitido
                  status:
                    type: integer
                    description: Código de estado HTTP
                    example: 405

components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: auth-token
      in: header
      description: Token de autenticación para acceder a la API

